//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGTY
    {
        public string TENCTY { get; set; }
        public Nullable<int> MASO_THUE { get; set; }
        public string DIA_CHI { get; set; }
        public string NGUOI_DD { get; set; }
        public string DIEN_THOAI { get; set; }
        public Nullable<System.DateTime> NGAY_HD { get; set; }
        public string LOAI_HINH { get; set; }
        public string TINH_TRANG { get; set; }
    }
}
