//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        public string TEN_HH { get; set; }
        public string MA_HH { get; set; }
        public Nullable<double> GIA { get; set; }
        public string NHA_CC { get; set; }
        public string XUAT_XU { get; set; }
        public string TINH_TRANG { get; set; }
    }
}
