//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO
    {
        public string MA_KHO { get; set; }
        public string TEN_KHO { get; set; }
        public string GMAIL { get; set; }
        public string SDT { get; set; }
        public string DIA_CHI { get; set; }
        public string TENCTY { get; set; }
    }
}
